"""add working hours to user

Revision ID: 3c883c24ffb2
Revises: 7a913e62e5bc
Create Date: 2026-03-14 01:23:21.692013

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3c883c24ffb2'
down_revision = '7a913e62e5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('work_start', sa.Integer(), nullable=False, server_default='9'))
    op.add_column('user', sa.Column('work_end', sa.Integer(), nullable=False, server_default='18'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'work_end')
    op.drop_column('user', 'work_start')
    # ### end Alembic commands ###
