"""add tags to task

Revision ID: 5940dedda093
Revises: 90565acf293d
Create Date: 2026-03-07 11:44:38.301861

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5940dedda093'
down_revision = '90565acf293d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'tags')
    # ### end Alembic commands ###
