"""add scheduled_start to task

Revision ID: 7a913e62e5bc
Revises: 5940dedda093
Create Date: 2026-03-14 00:18:01.079883

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7a913e62e5bc'
down_revision = '5940dedda093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('scheduled_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'scheduled_start')
    # ### end Alembic commands ###
