"""feat: implement task create and task reorder

Revision ID: 90565acf293d
Revises: d21fdb6c8905
Create Date: 2025-05-30 18:45:41.961628

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '90565acf293d'
down_revision = 'd21fdb6c8905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('position', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_position'), 'task', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_position'), table_name='task')
    op.drop_column('task', 'position')
    # ### end Alembic commands ###
