name: Lint Backend

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.15"
      - run: uv run bash scripts/lint.sh
        working-directory: backend

  # https://github.com/marketplace/actions/alls-green#why
  lint-backend-alls-green:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - lint-backend
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
